schema_version: 1.0.0
metadata:
  name: Task Breakdown Assistant
  description: "Break down a single task into a set of actionable subtasks with guidance."
  version: 0.1.0
  authors:
    - name: Example Developer
  license: MIT
app:
  entry_point: app.main:app
  inputs:
    task:
      type: string
      title: Task
      description: A single task description to break into subtasks.
      required: true
views:
  - id: task_breakdown_form
    type: form
    title: Break down a task
    description: Provide a task description to receive a structured breakdown.
    fields:
      - name: task
        title: Task description
        type: string
        required: true
        placeholder: Plan a team offsite
    submit_button_label: Break down task
    handler: break_down_task
